[project]
name = "inui"
version = "0.1.1"
authors = [
  { name="Mohammadreza Amani", email="more.amani@yahoo.com" },
]
description = "Powerful and Highly Customizable Python Library for UI"
readme = "README.md"
requires-python = ">=3.5"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/MohammadrezaAmani/INUI"
"Bug Tracker" = "https://github.com/MohammadrezaAmani/INUI/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = ['inui']